### ISSUE TITLE
I'm trying to use radzen Dropdown in  blog module bu I'm getting exceptions for Dynamic linque

### ISSUE THREAD

**Issue by shivampayasi01** [oqtane/oqtane.blogs#24]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.2.22.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.
File name: 'System.Linq.Dynamic.Core, Version=1.2.22.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'
   at Radzen.DropDownBase`1.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Radzen.RadzenComponent.SetParametersAsync(ParameterView parameters)
   at Radzen.DataBoundFormComponent`1.SetParametersAsync(ParameterView parameters)
   at Radzen.DropDownBase`1.SetParametersAsync(ParameterView parameters)
   at Radzen.Blazor.RadzenDropDown`1.SetParametersAsync(ParameterView parameters) @sbwalker

**Comment by sabitertan** [comment]
@shivampayasi01 , Can you please provide a demo repo so we can look at it?
